# install package
#  pip3 install pre-commit
# register as git commit-hook to run automatically
#  pre-commit install
# run manually
#  pre-commit run --all-files
# update hooks to latest version
#  pre-commit autoupdate

default_language_version:
  python: python3.13

exclude: |
  (?x)^(
    \.vscode/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      # - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      # - id: detect-aws-credentials
      - id: detect-private-key
      # conflict with black below
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
      # - id: file-contents-sorter
      #   files: ^(deploy-whitelist.txt|\.gitignore|\.dockerignore)$
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      # - id: forbid-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: name-tests-test
        args: ["--pytest-test-first"]
      # - id: no-commit-to-branch
      #   args: [--branch, staging]
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: requirements-txt-fixer
      # - id: sort-simple-yaml
      #  files: ^config/simple/
      - id: trailing-whitespace

  # Perl
  - repo: https://github.com/henryykt/pre-commit-perl
    rev: v0.0.5
    hooks:
      # - id: perlcritic
      - id: perltidy
      # - id: perlimports
