# install prek package (instead of python pre-commit)
#  brew install prek
# register as git commit-hook to run automatically
#  prek install
# run manually
#  prek run --all-files
# update hooks to latest version
#  prek autoupdate

exclude: |
  (?x)^(
    \.vscode/.*
  )$

repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-json5
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      # - id: deny-pattern  # custom regex
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^(cspell-words.txt)$
        args: ["--ignore-case"]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # - id: no-commit-to-branch # Prevent committing to protected branches
      #   args: [--branch, staging]
      # - id: pretty-format-json
      #   args: ["--autofix", "--indent=2", "--no-ensure-ascii", "--no-sort-keys"]
      # - id: require-pattern # Require each file to match a configured regular expression
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # security
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  # # ruff: moved to GH Action
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.15.1
  #   hooks:
  #     - id: ruff-check
  #       args: [--fix, --exit-non-zero-on-fix]
  #     - id: ruff-format

  # # markdown: moved to GH Action
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.49.0
  #   hooks:
  #     - id: markdownlint
  #       args: ["--disable", "MD013"]

  # # code spell check via cspell: moved to GH Action
  # - repo: https://github.com/streetsidesoftware/cspell-cli
  #   rev: v10.0.1
  #   hooks:
  #     - id: cspell

  # # Vulture: find dead code: moved to GH Action
  # - repo: https://github.com/jendrikseipp/vulture
  #   rev: v2.16
  #   hooks:
  #     - id: vulture
  #       pass_filenames: false
